tap "homebrew/core"
tap "homebrew/bundle"
tap "caskroom/cask"
brew "awscli"
brew "bash-completion"
brew "pyenv"
brew "pyenv-virtualenv"
brew "rbenv"
brew "tfenv"
brew "vagrant-completion"
brew "wget"
brew "the_silver_searcher"
cask "atom"
cask "iterm2"
cask "keepassx"
cask "vagrant"
cask "vagrant-manager"
cask "virtualbox"
"update"
"doctor"

