cask_args appdir: "/Applications"

tap "homebrew/core"
tap "homebrew/bundle"

brew "awscli"
brew "aws-shell"
brew "bash"
brew "bash-completion"
brew "diff-so-fancy"
cask "evernote"
brew "git"
cask "iterm2"
brew "jq"
cask "keepassx"
brew "kubernetes-cli"
brew "node"
brew "openssh"
brew "packer"
brew "pyenv"
brew "pyenv-virtualenv"
brew "python"
brew "pv"
brew "rbenv"
brew "the_silver_searcher"
brew "tree"
brew "tfenv"
brew "terraform-docs"
brew "vagrant-completion"
cask "vagrant"
cask "vagrant-manager"
cask "virtualbox"
brew "vim"
cask "visual-studio-code"
brew "wget"
brew "zsh"
brew "zsh-completions"
